# Generated by Django 4.1.7 on 2023-11-14 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_portfolio_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 14, 22, 7, 52, 115740)),
        ),
    ]
