# Generated by Django 4.2.5 on 2023-11-14 15:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(default='teacher.png', upload_to='team_members')),
                ('twitter', models.CharField(default='#', max_length=255)),
                ('instagram', models.CharField(default='#', max_length=255)),
                ('facebook', models.CharField(default='#', max_length=255)),
                ('linkdin', models.CharField(default='#', max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.skills')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('which_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.comment')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='portfolio')),
                ('image_2', models.ImageField(default='default.png', upload_to='portfolio')),
                ('image_3', models.ImageField(default='default.png', upload_to='portfolio')),
                ('title', models.CharField(max_length=90)),
                ('content', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('project_date', models.DateTimeField(default=datetime.datetime(2023, 11, 14, 18, 46, 25, 777706))),
                ('counted_views', models.IntegerField(default=0)),
                ('counted_like', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(to='portfolio.category')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.team_members')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='which_portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio'),
        ),
    ]
